protected/controllers/ProjectController.php
<?php
class ProjectController extends Controller
{
	public $layout='//layouts/column2';
    	
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}
	
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('setposition','view'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	public function actionView($id)
	{
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/dxcharts/jquery-2.0.3.min.js');
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/dxcharts/globalize.min.js', CClientScript::POS_END);
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/dxcharts/dx.chartjs.js', CClientScript::POS_END);
		$reportData = $this->get_index_project($id);
		$this->render('view',array(
			'reportData' => $reportData,
			'id' => $id
		));
	}
	
	public function actionSetPosition(){
	    //print YiiBase::getPathOfAlias('application.components');die;
		$day = date('d',time());

		$current_date =  mktime(0,0,0,date('m',time()), $day-18, date('Y',time()));
		$last_date =  mktime(0,0,0,date('m',time()), $day-16, date('Y',time()));
		$report = new SeoBud($current_date, $last_date);
		$report->sb_set_position();
	}
	
	public function get_index_project($project_id){
		$sql = "SELECT * FROM `srep_index` `si`
			INNER JOIN `srep_group` `sg` ON `sg`.`id` = `si`.`id_group`
			INNER JOIN `srep_project` `spr` ON `spr`.`id` = `sg`.`id_project`
			WHERE `sg`.`id_project` = :project_id
			ORDER BY `sg`.`id_project`, `si`.`date`
		";
		$connection=Yii::app()->db;
		$command=$connection->createCommand($sql);
		$command->bindParam(":project_id",$project_id,PDO::PARAM_STR);
		$result = $command->queryAll();
		foreach($result as $data){
		    
			$fdate = Yii::app()->dateFormatter->formatDateTime($data['date'],'full',null);
			$indexses['groups'][$data['id_group']][$fdate]['name'] = $data['gr_name'];
			$indexses['groups'][$data['id_group']][$fdate]['ya'] = (int)$data['ya_index'];
			$indexses['groups'][$data['id_group']][$fdate]['goog'] = (int)$data['goog_index'];
			$indexses['groups'][$data['id_group']][$fdate]['sum'] = (int)$data['goog_index']+(int)$data['ya_index'];
			$indexses['groups'][$data['id_group']][$fdate]['date'] = $fdate;
			$indexses['projects'][$data['id_project']][$fdate]['name'] = $data['pr_name'];
			$indexses['projects'][$data['id_project']][$fdate]['ya'] += (int)$data['ya_index'];
			$indexses['projects'][$data['id_project']][$fdate]['goog'] += (int)$data['goog_index'];
			$indexses['projects'][$data['id_project']][$fdate]['sum'] += (int)$data['goog_index']+(int)$data['ya_index'];
			$indexses['projects'][$data['id_project']][$fdate]['date'] = $fdate;
			$project_name = $data['pr_name'];
		}
		$data['data'] = $indexses;
		$data['pr_name'] = $project_name;
		return $data;
	}
}

protected/controllers/ReportController.php
<?php
class ReportController extends Controller
{
	public function actionView($id)
	{
		Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/css/report.css');
		/*Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/js/tooltipster/css/tooltipster.css');
		Yii::app()->clientScript->registerCssFile(Yii::app()->baseUrl.'/js/tooltipster/css/themes/tooltipster-shadow.css');
		Yii::app()->getClientScript()->registerCoreScript('jquery');
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/tooltipster/js/jquery.tooltipster.min.js', CClientScript::POS_END);
		Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/scriptReport.js', CClientScript::POS_END);*/
		$report= new Report($id);
		$reportData = $report->create_report();
		$project = SrepProject::model()->findByPk($id);
		$sql_date = "SELECT DISTINCT `si`.`date` FROM `srep_index` `si`
		    INNER JOIN `srep_group` `sg` ON `sg`.`id` = `si`.`id_group`
		    WHERE `sg`.`id_project` = :project_id
		    ORDER BY `si`.`date` DESC
		    LIMIT 2
		    ";

		$connection=Yii::app()->db;
		$command=$connection->createCommand($sql_date);
		$command->bindParam(":project_id",$id,PDO::PARAM_STR);
		$last_date = $command->queryColumn();
		$this->render('view',array(
			'reportData' => $reportData,
			'project' => $project,
			'date_up' =>$last_date
		));
	}
	
	
}

protected/views/report/view.php
<?php 
$this->breadcrumbs=array(
	$project['pr_name'],
);

$count = count($reportData);
?>
<p class="date-up">Отчет <?php echo Yii::app()->dateFormatter->formatDateTime($date_up[1],'medium',null) ." — ".Yii::app()->dateFormatter->formatDateTime($date_up[0],'medium',null)?></p>
<table class="report-tbl">
    <thead>
	<tr class="top-tr"> 
	    <th></th>
	    <th colspan=3>Эффективных показов</th> 
	    <th colspan=3>Позиции в Яндекс</th> 
	    <th colspan=3>Позиции в Google</th> 
	    <th colspan=3>Видимость</th> 
	    <th>График</th> 
	</tr>
	<tr>
	    <th></th>
	    <th>Всего</th>
	    <th>Яндекс</th>
	    <th>Google</th>
	    <th>1-3</th>
	    <th>4-10</th>
	    <th>11<</th>
	    <th>1-3</th>
	    <th>4-10</th>
	    <th>11<</th>
	    <th>Общая</th>
	    <th>в Яндекс</th>
	    <th>в Google</th>
	    <th></th>
	</tr>
    </thead>
    <tbody>
	
	<?php 
	    $out = "";
	    foreach($reportData as $gr_name=>$data){	   
		$out .=  "<tr>";
		if($gr_name=='project') $gr_name = $project['pr_name'];
		$out .=  "<td class='name'>".$gr_name."</td>";
		
		$out .=  "<td>".$data['effect_sum']." (".positiv($data['effect_sum_raz']).")</td>";
		$out .=  "<td>".$data['effect_ya']." (".positiv($data['effect_ya_raz']).")</td>";
		$out .=  "<td>".$data['effect_goog']." (".positiv($data['effect_goog_raz']).")</td>";
		
		$out .=  "<td>".(($data['positions_ya'][1]) ? $data['positions_ya'][1] : 0)."</td>";
		$out .=  "<td>".(($data['positions_ya'][2]) ? $data['positions_ya'][2] : 0)."</td>";
		$out .=  "<td>".(($data['positions_ya'][3]) ? $data['positions_ya'][3] : 0)."</td>";
		
		$out .=  "<td>".(($data['positions_goog'][1]) ? $data['positions_goog'][1] : 0)."</td>";
		$out .=  "<td>".(($data['positions_goog'][2]) ? $data['positions_goog'][2] : 0)."</td>";
		$out .=  "<td>".(($data['positions_goog'][3]) ? $data['positions_goog'][3] : 0)."</td>";
		
		$out .=  "<td>".$data['view_pos_sum']."% (".positiv($data['view_pos_sum_raz'])."%)</td>";
		$out .=  "<td>".$data['view_pos_ya']."% (".positiv($data['view_pos_ya_raz'])."%)</td>";
		$out .=  "<td>".$data['view_pos_goog']."% (".positiv($data['view_pos_goog_raz'])."%)</td>";
		if(!empty($data['group_id'])){
		    $out .=  "<td>". CHtml::link('ссылка',$this->createUrl('/project/view', array('id'=>$project['id'], '#'=>'group_'.$data['group_id'])))."</td>";
		}else{
		    $out .=  "<td>". CHtml::link('ссылка',$this->createUrl('/project/view', array('id'=>$project['id'])))."</td>";
		}
		$out .=  "</tr>";
	    }
	    print $out;
	?>
		
    </tbody>
</table>